spring:
  application:
    name: rotatoy
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: rotatoy
  banner:
    location: 'classpath:/banner.txt'
server:
  port: '8081'
management:
  endpoints:
    web:
      exposure:
        include: 'health,info'
  endpoint:
    health:
      show-details: always
claude:
  api:
    key: ${API_KEY} 
    
logging:
  level:
    root: INFO
    org:
      springframework:
        web: DEBUG
    com:
      example: TRACE
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
